In [1]:
# coding: UTF-8
import argparse
import logging
import os
import random
import sys
from datetime import datetime
from posixpath import join

import faiss
import numpy as np
import pandas as pd
# using labse
# from transformers import *
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.utils.data as Data
from torch.nn import *
sys.path.append('..')
from loader.DBP15KRawNeighbors import DBP15KRawNeighbors
from script.preprocess.deal_raw_dataset import MyRawdataset
from settings import *
from model.layers_LaBSE_neighbor import *

sys.argv=['']
del sys

### model

MyEmbedder: 继承nn.module

### update函数 
momentum = 0.9999
key*0.9999 + 0.0001*query

In [2]:
parser = argparse.ArgumentParser()
args = parse_options(parser)
model = MyEmbedder(args, VOCAB_SIZE)
modelS = MyEmbedder(args,VOCAB_SIZE)
list(model.parameters())

[Parameter containing:
 tensor([[[ 0.0008,  0.0008,  0.0014,  ...,  0.0016, -0.0016,  0.0020],
          [ 0.0015,  0.0016,  0.0007,  ..., -0.0030,  0.0016, -0.0024],
          [ 0.0019,  0.0020,  0.0012,  ...,  0.0023, -0.0006,  0.0026],
          ...,
          [-0.0031,  0.0030,  0.0012,  ...,  0.0019, -0.0007, -0.0004],
          [-0.0013, -0.0020,  0.0027,  ..., -0.0022,  0.0011, -0.0016],
          [ 0.0014, -0.0013, -0.0008,  ...,  0.0001,  0.0015, -0.0008]]],
        requires_grad=True),
 Parameter containing:
 tensor([[[ 4.8053e-02],
          [ 5.8063e-02],
          [-2.6044e-02],
          [ 5.9896e-02],
          [-1.7188e-02],
          [ 4.9931e-02],
          [-1.9969e-02],
          [-2.9880e-02],
          [-8.0305e-02],
          [-7.5988e-02],
          [-6.1418e-02],
          [-1.5593e-02],
          [-2.9537e-02],
          [ 4.0869e-02],
          [ 7.7976e-02],
          [ 2.6991e-02],
          [ 5.5513e-02],
          [-1.4730e-02],
          [ 6.7259e-02],
 

In [22]:
model.eval()

MyEmbedder(
  (attn): BatchMultiHeadGraphAttention(
    (leaky_relu): LeakyReLU(negative_slope=0.2)
    (softmax): Softmax(dim=-1)
    (dropout): Dropout(p=0.3, inplace=False)
  )
  (attn_mlp): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
  )
  (criterion): NCESoftmaxLoss(
    (criterion): CrossEntropyLoss()
  )
)

In [23]:
model.state_dict()

OrderedDict([('attn.w',
              tensor([[[-6.9449e-04,  2.6912e-03, -4.6595e-04,  ..., -2.8645e-03,
                         2.4195e-03, -6.6257e-04],
                       [-1.0049e-03, -5.0237e-04, -1.4626e-03,  ..., -2.5157e-03,
                         8.5154e-04, -9.8197e-04],
                       [ 1.5551e-03, -1.6492e-03, -1.3634e-03,  ..., -2.5297e-03,
                         6.2598e-04,  2.8866e-04],
                       ...,
                       [ 1.0801e-03, -1.4021e-03,  5.3374e-04,  ..., -4.2688e-04,
                        -1.6067e-03, -2.4894e-03],
                       [ 6.0395e-05, -5.3561e-04,  2.8277e-03,  ..., -3.7410e-04,
                         3.0223e-03,  1.1275e-03],
                       [-6.9074e-04, -1.6215e-03, -7.1493e-04,  ..., -2.4690e-03,
                         1.7762e-04, -2.1898e-03]]])),
             ('attn.a_src',
              tensor([[[ 0.0814],
                       [-0.0721],
                       [-0.0458],
                

In [24]:
model.state_dict().keys()

odict_keys(['attn.w', 'attn.a_src', 'attn.a_dst', 'attn.bias', 'attn_mlp.0.weight', 'attn_mlp.0.bias'])

model.parameters()就是模型的两层，分别是attn的四个参数和mlp的两个参数

In [25]:
for key_param, query_param in zip(model.parameters(), modelS.parameters()):
    print(key_param.shape)
    
    key_param.data *= model.args.momentum
    key_param.data += (1 - model.args.momentum) * query_param.data

torch.Size([1, 768, 768])
torch.Size([1, 768, 1])
torch.Size([1, 768, 1])
torch.Size([768])
torch.Size([768, 1536])
torch.Size([768])


### MyEmbedder.forward

